version: "3.8"

services:
#  postgres:
#    image: postgres:16
#    container_name: osint_postgres
#    environment:
#      POSTGRES_DB: osintdb
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
  app:
    build:
      context: ./app
    container_name: osint_kotlin_app
    depends_on:
      theharvester:
        condition: service_healthy
      amass:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/osintdb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DRIVER: org.postgresql.Driver
    volumes:
      - ./scan_results:/data/harvester-results
      - ./scan_results:/data/amass-results

  theharvester:
    build:
      context: ./theharvester
    container_name: theharvester_runner
    ports:
      - "9001:9001"
    volumes:
      - ./scan_results:/data/harvester-results

  amass:
    build:
      context: ./amass
    container_name: amass_runner
    ports:
      - "9000:9000"
    volumes:
      - ./scan_results:/data/amass-results

volumes:
  pgdata:
